### ISSUE TITLE
Mixes 'winners scoreboard' and 'entire scoreboard'

### ISSUE THREAD

**Issue by Meklon2007** [relarn/relarn#2]
Hello, my scoreboard not does not contain winning characters.
If i run whith -s key, program give me entire list:
![winner](https://github.com/relarn/relarn/assets/12417354/5d50de2d-a0e4-441b-97a9-32b00097f181)

If i run whith -i key, program give me empty list:

![entire](https://github.com/relarn/relarn/assets/12417354/0714766c-7ece-4146-ae6e-255dee243cb1)

**Comment by suetanvil** [comment]
This is fixed as of release 2.2.2.  Thanks for the bug report.
