### ISSUE TITLE
Maybe bug when sell gems in bank

### ISSUE THREAD

**Issue by Meklon2007** [relarn/relarn#4]
When i sell stones in a bank, their value is displayed (in the example 1100 GP):
![sell_witch](https://github.com/relarn/relarn/assets/12417354/b5c78e84-1657-48b2-b6de-c60422f04251)

On the second screen, the resulting amount is correct (1100 GP), but for some reason the cost is different (220), a little confusing (maybe it should be like that):

![sell_screen2](https://github.com/relarn/relarn/assets/12417354/9310bfdc-ad7c-4ed2-998e-85050cdc8ca7)

**Comment by suetanvil** [comment]
Aha.  It turns out it's showing the store price instead of the bank price.  That's a trivial fix.

**Comment by suetanvil** [comment]
This is now fixed in release 2.2.2.
